### ISSUE TITLE
add pip installation

### ISSUE THREAD

**Issue by keiyamamo** [KVSlab/VaSP#123]
making it possible to download vasp with pip

**Comment by keiyamamo** [comment]
@jorgensd Do you think making `VaSP` installable via pip is feasible? `VaSP` needs `turtleFSI`, which needs fenics 2019. We also need VMTK, which is not available via pip.

**Comment by jorgensd** [comment]
It can be put on pip, but not with FEniCS or VMTK in its dependency list, as the wheels won’t build with them.

**Comment by keiyamamo** [comment]
In that case, users need to download both FEniCS and VMTK separately? I don’t really see the benefits of putting it on pip in that case.

**Comment by jorgensd** [comment]
Yes, that would be the case. I don’t see a big benefit of putting it on pip. However, VASP on conda would be beneficial.

**Comment by keiyamamo** [comment]
Thanks! Agreed, I will consider putting it on conda first.
