### ISSUE TITLE
`print_mesh_summary` not correct with MPI

### ISSUE THREAD

**Issue by keiyamamo** [KVSlab/VaSP#144]
https://github.com/KVSlab/VaSP/blob/14bc890b71d1e60703683039c6bd4168eef867d4/src/vasp/simulations/simulation_common.py#L47

I noticed that coordinate range is wrong when running with MPI. This is because we are taking the `sum` instead of `min` or `max`.

https://github.com/KVSlab/VaSP/blob/14bc890b71d1e60703683039c6bd4168eef867d4/src/vasp/simulations/simulation_common.py#L90

@johannesring  There is basically the same function in `VaMPy`, but `VaMPy` one does not have this problem. Should we remove `print_mesh_summary` from `VaSP` and use the one from `VaMPy`? Was there particular reason you made this function in `VaSP`?

**Comment by johannesring** [comment]
I think I added it because at that time it was not possible to import things from VaMPy. We can remove it and import the one in VaMPy instead.

**Comment by keiyamamo** [comment]
I see. Thanks for the input!
