### ISSUE TITLE
add a function to flatten the inlet/outlet

### ISSUE THREAD

**Issue by keiyamamo** [KVSlab/VaSP#172]
Based on our internal discussion, it seems critical to have a flat inlet/outlet. I’m guessing it is something that we can perform after generating volume mesh.

**Comment by dbruneau-mie** [comment]
I have made a pull request for a script that does this after checking whether it is flat or not. May make sense to eventually grow this into a mesh quality checker as well (aspect ratio of fluid and solid elements).

**Comment by keiyamamo** [comment]
Closed with #176. Will merge into the main meshing script.
